name = "tauri-update-server"
workers_dev = true
compatibility_date = "2022-03-26"
main = "src/index.ts"

routes = [
    { pattern = "updates.overseers-manual.dwarffortress.nwest.games", custom_domain = true },
    { pattern = "overseers-manual-df.updates.nwest.one", custom_domain = true },
]

[vars]
GITHUB_ACCOUNT = 'nwesterhausen'
GITHUB_REPO = 'overseers-manual-df'
GITHUB_TOKEN = ''                   # Optional - used with private repos

[build]
command = "npm install && npm run build"
