name = "tauri-update-server"
workers_dev = true
compatibility_date = "2023-10-24"
main = "src/index.ts"

routes = [
    { pattern = "overseers-manual-df.updates.nwest.one", custom_domain = true, zone_name = "nwest.one" },
]

[vars]
GITHUB_ACCOUNT = 'nwesterhausen'
GITHUB_REPO = 'overseers-manual-df'
GITHUB_TOKEN = ''                   # Optional - used with private repos

[build]
command = "npm install && npm run build"
